### ISSUE TITLE
Mobile chat has serious bugs

### ISSUE THREAD

**Issue by Coloradorks** [pichalite/nodebb-theme-material#12]
Right now, clicking on the chat icon in the top-right on a xs display causes the chat popup to open. This is problematic, as the pop-up chat does not function on mobile at all, causing issues such as overflow and text below the visible area.

However, the full chat functions perfectly for mobile.

I suggest that when in a xs view, the chat bubble becomes a link to /chats

**Comment by pichalite** [comment]
chat popup works fine for me on mobile at pichalite.com

What issues are you seeing? screenshots?

**Comment by pichalite** [comment]
@Coloradorks ?

**Comment by LordZardeck** [comment]
This is not the best experience on mobile. Had to really guide my community users to get them to be able to use this. 

A better experience on mobile would be to lock the scrolling, and have it extend to all edges of the screen. Possibly still showing the menu, but any navigation would need to close or minimize the chat. Also, a link to go to the all chats page, opening this conversation might also be good. If this is something you would be interested in, I can make a PR.

![screenshot_2016-01-12-14-47-59](https://cloud.githubusercontent.com/assets/1145989/12276791/f82f6eda-b934-11e5-97e3-4d5c8f1b2e23.png)

**Comment by LordZardeck** [comment]
@pichalite I'd checkout my solution in my pull requests. There's a couple of other issues your changes don't fix:
1. The chatbox is not at the bottom, giving a weird feeling of empty space:
   ![testuser nodebb 2016-01-12 22-21-31](https://cloud.githubusercontent.com/assets/1145989/12285773/daf1095a-b97a-11e5-81dc-41664952c204.png)
2. There is also the issue that the chatbox doesn't expand as you type multiple lines of text in. My changes take account of this and expand the textarea as multiple lines are added.

**Comment by LordZardeck** [comment]
Plus, the border radius at the top looks funky when going full screen

**Comment by pichalite** [comment]
I will take a look at these. Not sure if I want to add another library just to resize textbox.

**Comment by LordZardeck** [comment]
@pichalite Well, it's a very small library. NodeBB actually already has it loaded, but it's an older version that doesn't seem to work on this. That being said, it's lazy loaded and small. Probably should have minified it though

**Comment by Coloradorks** [comment]
@pichalite (Deeply sorry for never replying, I now have github set up to email me when I get a reply! Issue seems fixed, though.)
