### ISSUE TITLE
Avatar editing hard for users to discover

### ISSUE THREAD

**Issue by Coloradorks** [pichalite/nodebb-theme-material#13]
Right now under the Edit Profile page:

http://pichalite.com/user/admin/edit

There is, under the avatar, a mysterious button with two arrows, facing different directions. This icon has little meaning to the user, and confuses users who aren't aware how to change their avatar, hiding functionality.

I suggest the drop down be removed entirely, bringing it more in line with Persona:

https://community.nodebb.org/user/pichalite/edit

Simply having the four menu items exposed to the user without a drop down.

If that is undesired, I suggest changing the two arrows into a cogs icon, that more traditionally indicates settings.

**Comment by pichalite** [comment]
I didn't want to add 4-5 buttons to the screen so made it into a dropdown. The options are not actually settings so, didn't want to use the cogs icon.

May be I can change it to say "Options". What do you think? @Coloradorks

**Comment by Coloradorks** [comment]
"Options" would work fine! Anything that would make it more obvious to the user to click that.
