### ISSUE TITLE
Post editor is clipped out of window

### ISSUE THREAD

**Issue by ghost** [pichalite/nodebb-theme-material#17]
This happens in both Safari 9 and Firefox on OS X, I don't know if it happens elsewhere (notice how the scrollbar and text doesn't end at the bottom of the window, but continues off the bottom of the window.)

I did a bit of digging in the CSS and experimented with disabling various paddings and margins in particular UI elements of the post editor to see if they were causing it, I thought that was the issue, but when I resize the post editor with them disabled, the text boxes resize and clip outside the window again, so I'm not sure.

![screen shot 2016-01-06 at 04 35 29](https://cloud.githubusercontent.com/assets/13513775/12135129/2a4fd1a8-b42f-11e5-8129-8aea3fa6a285.png)
![screen shot 2016-01-06 at 04 35 37](https://cloud.githubusercontent.com/assets/13513775/12135131/2d4369ec-b42f-11e5-8654-4a7809db966d.png)

Great theme btw! I'm really liking it :3.

**Comment by pichalite** [comment]
@mikhto Composer is a plugin. Please post it in the composer plugins repo. Looks the same on https://community.nodebb.org too?

**Comment by ghost** [comment]
Ah, okay, it's just that I didn't have this issue on other themes, so I assumed it was something to do with this one.

ie. Persona theme (latest version):
![screen shot 2016-01-08 at 00 07 21](https://cloud.githubusercontent.com/assets/13513775/12186548/d02c4580-b59b-11e5-8d34-4266c46dc714.png)

**Comment by pichalite** [comment]
@mikhto sent a PR to the composer plugin, waiting for it to be merged.

In the mean time you can do one thing... click and hold the expand icon on the top left corner of the composer and drag up until the text boxes are completely visible and stop. The composer will save the position and will stay there.

**Comment by ghost** [comment]
@pichalite, okay, thanks for the tip. Sorry for the mixup.

**Comment by pichalite** [comment]
fixed upstream in the composer plugin. You will have to wait for NodeBB v1.0.0 though.

nodebb/nodebb-plugin-composer-default#15
