### ISSUE TITLE
Gravatar profile images very large

### ISSUE THREAD

**Issue by aggied** [pichalite/nodebb-theme-material#2]
Great template! In the topic feed, gravatar images are excessively large. I assume that is not supposed to be the case? I can take a look at some CSS tweaks

![image](https://cloud.githubusercontent.com/assets/4122815/8667005/331b3630-29c7-11e5-898e-5ed823b7cd92.png)

**Comment by pichalite** [comment]
@aggied What version of the theme are you using? Is your site public so that I can take a look?

**Comment by aggied** [comment]
@pichalite 2.0.8 according to the admin section. Just running locally ATM, but will probably get it online in the near future.

**Comment by pichalite** [comment]
I don't think you are using version 2.0.8 because the topic page doesn't look like that in version 2. Can you post a screenshot of the full page and a screenshot of the plugin page in admin section?

**Comment by aggied** [comment]
Apologies -- I needed to clear the cache w/ a simple hard refresh and everything looked great! I'll close this out.
