### ISSUE TITLE
Composer opening and closing is sporadic, and for some reason tries to start maximized

### ISSUE THREAD

**Issue by Coloradorks** [pichalite/nodebb-theme-material#23]
http://i.imgur.com/3gBM1Zp.gifv

The composer in Material often tries to open maximized for some reason, and then does the above when it tries to minimize again. Further, when this bug occurs, the discard confirmation appears under the composer, meaning a maximized post cannot be dismissed.

This issue appears to occur when the composer overlaps the navigation bar, and is confirmed to occur on pichalite.com as well, just to confirm I didnt break anything myself!

http://i.imgur.com/GFJgJRD.png

Resizing the window and pounding the button, then resizing and pounding the button, eventually fixes it.

This issue does not occur in Persona. It might be related to the fact persona's maximized state snaps to the navigation bar itself?

**Comment by pichalite** [comment]
@Coloradorks  It's an issue with the composer plugin `nodebb-plugin-composer-default`. The plugin has code that tries to calculate height and positioning of the composer based on some elements present on the page.  Mostly based on persona. If third party themes don't have those elements where persona has them... the calculation goes wrong. I ran into the maximize/minimize issues on persona too in certain conditions. Not sure what the solution is here.

**Comment by pichalite** [comment]
@Coloradorks P.S. pichalite.com will not be hosting a demo for the theme anymore. In a few days, my DO account will run out of funds and I am not planning to add funds to it. Don't want to keep paying for hosting a demo for a free theme.

**Comment by Coloradorks** [comment]
@pichalite Thats sad to hear- could something like openshift work if you removed the activity bots?

Also: I found a partial solution by modifying user behavior with a UI change to the composer on my site- it seems to be working well, so far.

**Comment by pichalite** [comment]
should be fixed in composer plugin if not post there
