### ISSUE TITLE
Sidebar cannot be pulled in on mobile

### ISSUE THREAD

**Issue by Coloradorks** [pichalite/nodebb-theme-material#25]
Reporting this one as it's a fairly simple fix with a big usability boost for mobile users.

If you visit a site running persona, and drag in from the right, you'll notice the sidebar drags smoothly in, via:

https://github.com/NodeBB/nodebb-theme-persona/blob/master/lib/modules/slideout.min.js

Something similar would be hugely beneficial to the mobile use of this theme.

**Comment by pichalite** [comment]
@Coloradorks adding sidebar brings lot of other issues so, don't think I will be adding this to the theme.
