### ISSUE TITLE
Editor not completely visible

### ISSUE THREAD

**Issue by linuxundich** [pichalite/nodebb-theme-material#28]
When I edit longer postings with Chrome as browser, I can't see the last line.

![editor](https://cloud.githubusercontent.com/assets/1716643/12731975/b1c24238-c933-11e5-8202-50351b0269da.png)

**Comment by pichalite** [comment]
this an issue with the composer plugin not the theme itself. See details here...

https://github.com/pichalite/nodebb-theme-material/issues/17

**Comment by linuxundich** [comment]
Ah ok, thanks.
