### ISSUE TITLE
Stop using html in translated string

### ISSUE THREAD

**Issue by ishitatsuyuki** [pichalite/nodebb-theme-material#29]
See this https://github.com/NodeBB/NodeBB/commit/99315e1c737c4a6261407bee18ae326be9e69171 .

One example for the wrong code:
https://github.com/pichalite/nodebb-theme-material/blob/master/templates/partials/topics_list.tpl#L44

**Comment by pichalite** [comment]
We have a PR for that https://github.com/pichalite/nodebb-theme-material/pull/24

Will be merged and updated as part of updates for NodeBB v1.0
