### ISSUE TITLE
The html is appear

### ISSUE THREAD

**Issue by skywalker512** [pichalite/nodebb-theme-material#30]
![2016-02-10 22 04 43](https://cloud.githubusercontent.com/assets/12960906/12949393/868e2f58-d042-11e5-8e84-f87b8581f5e5.png)

**Comment by pichalite** [comment]
are you using NodeBB master?

**Comment by pichalite** [comment]
`git rev-parse HEAD`

**Comment by skywalker512** [comment]
I use releases v0.9.3 to install

**Comment by pichalite** [comment]
what's the output of `git rev-parse HEAD`?

**Comment by skywalker512** [comment]
git rev-parse HEAD is be38cf075acd51d55929853cfa1d0f7ce66aabc4
I  install nodebb on the openshift.
So this HEAD maybe is openshift's.

**Comment by pichalite** [comment]
that's not a valid commit hash for NodeBB. Anyway there was a change in master branch that would make it an issue and the theme is not updated for master. You are using the master branch of NodeBB and the theme won't be updated for master branch of NodeBB. Only stable releases are supported.
