### ISSUE TITLE
material-load-bar infinity animation power usage

### ISSUE THREAD

**Issue by iDevPro** [pichalite/nodebb-theme-material#32]
`material-load-bar`

before remove this item:
<img width="1227" alt="2016-03-07 23 29 15" src="https://cloud.githubusercontent.com/assets/1888230/13582328/d487edfa-e4bc-11e5-823d-a0d6fe520d61.png">

after remove:
<img width="1224" alt="2016-03-07 23 30 06" src="https://cloud.githubusercontent.com/assets/1888230/13582348/e6584e94-e4bc-11e5-890a-66b5eff17c26.png">

**Comment by pichalite** [comment]
don't think it's because of the material-load-bar. switch to a different theme persona or something and monitor power usage. most likely reason is web sockets.

**Comment by pichalite** [comment]
8.7 is nothing. try inbox.google.com it will be in the hundreds. this is not an issue.
