### ISSUE TITLE
when reply to topic by mobile ,there will be an error  that : compose/undefined/undefined

### ISSUE THREAD

**Issue by woniu127** [pichalite/nodebb-theme-material#34]
![wcj0ilv](https://cloud.githubusercontent.com/assets/17917275/14643344/a64b0e3c-0680-11e6-9b10-91e15cc063cb.jpg)

**Comment by pichalite** [comment]
@gaokaigithub do you have steps to reproduce the issue?

**Comment by pichalite** [comment]
can't reproduce
