### ISSUE TITLE
Topic tools button displayed even if it is empty.

### ISSUE THREAD

**Issue by Haocen** [pichalite/nodebb-theme-material#37]
<img width="374" alt="topic tools" src="https://cloud.githubusercontent.com/assets/10842569/15251770/eed5a862-18f8-11e6-813d-9e529a61d948.png">

**Comment by pichalite** [comment]
@Haocen did you test it using persona to make sure it's not a theme related issue? Do you have any reproduction steps?

**Comment by Haocen** [comment]
I've allowed guest to post new topic, but not to report in this category, but I tested on persona, the problem is still there, I guess it's related to NodeBB itself.
