### ISSUE TITLE
Autocomplete menus in separate route composer start in the wrong place

### ISSUE THREAD

**Issue by bdharrington7** [pichalite/nodebb-theme-material#41]
Moved from https://github.com/NodeBB/nodebb-plugin-composer-default/issues/43:

The behavior of the autocomplete dropdown for both @Mentions and emojis is broken.

On a fresh page render, (on desktop, you can't even see it on mobile at this point) typing @ renders the dropdown at the bottom of the page
Subsequent characters added move the dropdown closer and closer to the cursor, eventually getting to the right place in about 3 characters. 3a. Subsequent renders of the autocomplete dropdown show it in the right position 3b. A Refresh will show reproduce the issue
on first render, I can see this:
![](https://cloud.githubusercontent.com/assets/4553795/15660793/a5158940-2695-11e6-99af-10e7163ac074.png)
![](https://cloud.githubusercontent.com/assets/4553795/15660797/b26cd850-2695-11e6-9181-f6eba3a1e1f0.png)

the `top:` attribute is incorrectly calculated at 667px

OSX Chrome
iOS safari

**Comment by pichalite** [comment]
I am not sure how to handle this. All the layout for the composer is handled by the composer plugin.

**Comment by bdharrington7** [comment]
In my testing, this only happens in the material theme

**Comment by pichalite** [comment]
I know. That's why I said I am not sure how to fix this.

**Comment by pichalite** [comment]
emojis seem to be fine. I don't see any issue with them.

**Comment by pichalite** [comment]
@bdharrington7 should be fixed now. try the new version.

**Comment by bdharrington7** [comment]
@pichalite Thank you for looking at this, I'll try it out as soon as possible!
