### ISSUE TITLE
But with Youtube Embed

### ISSUE THREAD

**Issue by Master-Antonio** [pichalite/nodebb-theme-material#45]
Plugin : nodebb-plugin-youtube-embed
There is a little bug of graphic in the groups with the theme  : Material Design Theme.
Theme Link : https://github.com/pichalite/nodebb-theme-material#readme
![image](https://cloud.githubusercontent.com/assets/9674957/17950914/a34a5c50-6a5e-11e6-8e25-c1813696ceb9.png)
![image](https://cloud.githubusercontent.com/assets/9674957/17950924/b10ea5c6-6a5e-11e6-930a-1990958a7b08.png)

**Comment by pichalite** [comment]
issues created by third party plugins are not the themes problem. post it on the plugins repo.

**Comment by Master-Antonio** [comment]
I was wrong chat.
