### ISSUE TITLE
Large display issue

### ISSUE THREAD

**Issue by drewdotpro** [pichalite/nodebb-theme-material#5]
On very large screens the blue doesn't go all the way:
![upload-6e42c8bd-1c20-49ac-aa6f-c86a5eae61aa](https://i.imgur.com/91zjQqR.png)

Screen 2560x1600.

**Comment by Coloradorks** [comment]
If you mean that it doesnt go all the way down, that is an intentional style I think?

You can change it in the CSS though

**Comment by pichalite** [comment]
@drewdotpro the blue background is only supposed to be filled 50%. The login block needs to be aligned center vertically. Should be fixed now.

**Comment by pichalite** [comment]
the login and register pages are now modified in the new version and do not have two different colors on the page so, closing this.
