### ISSUE TITLE
Change font to latin extended

### ISSUE THREAD

**Issue by kubaboski** [pichalite/nodebb-theme-material#54]
How to add latin extended to the font ?

**Comment by pichalite** [comment]
You will have to change this file to import the font and apply it to the body tag.

https://github.com/pichalite/nodebb-theme-material/blob/master/less/style.less

**Comment by kubaboski** [comment]
I've managed to do it another way. I've added to Custom CSS 

`@import url(https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&subset=latin-ext);`
