### ISSUE TITLE
emoji bug

### ISSUE THREAD

**Issue by lmislm** [pichalite/nodebb-theme-material#57]
i install nodebb-plugin-emoji-extended and nodebb-plugin-emoji-one,but none can work,when i reply, the emoji icon can't show;

**Comment by pichalite** [comment]
Do they work if you switch to persona theme?

**Comment by lmislm** [comment]
No. i try to switch all of the main theme，but it doesn't work.i try to install the theme and the plugin  again,it still so.I can't understand where the problem.

**Comment by lmislm** [comment]
and another thing is,if i can move the chat windows,that will be awsome.i wish you can add this function.

**Comment by lmislm** [comment]
I wish the problem will be resolve,i think this function is very important.But i don't know why the bug disappear,Is my set error？

**Comment by pichalite** [comment]
It's not a problem with the theme then if it doesn't work on persona too. Post on https://community.nodebb.org for help with the emoji plugin.

**Comment by lmislm** [comment]
thank you
