### ISSUE TITLE
Topic's title input is small

### ISSUE THREAD

**Issue by SaitDev** [pichalite/nodebb-theme-material#59]
When making a new topic, we cant see the full title that we typed

Screenshot: http://prnt.sc/ey0sq7

**Comment by pichalite** [comment]
@SaitDev that's an issue with the composer. Composer provides it own styling. All this theme does to composer is change colors.

You need to report the issue on the composer plugin repo.

**Comment by SaitDev** [comment]
I see, thanks for the info
