### ISSUE TITLE
Home page doesn't load after applying theme.

### ISSUE THREAD

**Issue by azariah001** [pichalite/nodebb-theme-material#6]
High, I really liked the look of your theme on `0.7.2` of the forum but I've just updated to `0.7.3` and now I'm getting a Redis error in my log every-time I try to load the home page. :disappointed: The error basically means that no content is loaded onto the page at all other than the template with the navbar and footer.

Here's the error readout.

```
20/8 07:49 [2630] - [31merror[39m: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED
    at RedisClient.on_error (/root/node_modules/redis/index.js:185:24)
    at Socket.<anonymous> (/root/node_modules/redis/index.js:95:14)
    at Socket.emit (events.js:107:17)
    at net.js:459:14
    at process._tickDomainCallback (node.js:381:11)
[cluster] Child Process (2630) has exited (code: 1, signal: null)
[cluster] Spinning up another process...
20/8 07:49 [2747] - info: Time: Thu Aug 20 2015 07:49:17 GMT-0400 (EDT)
20/8 07:49 [2747] - info: Initializing NodeBB v0.7.3
```

Everything works fine in other themes, Lavender and Vanilla.

Theme version is `2.2.0`

**Comment by pichalite** [comment]
@azariah001 theme v2.2.0 is only compatible with NodeBB V0.7.2. Anyway the error doesn't seem to be related to the theme. I had other users update to NodeBB v0.7.3 without any issue and I myself didn't see any issues.

`Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED`

You seem to have an issue with your Redis connection.

Theme is now updated for NodeBB v0.7.3, try the new version and let me know if you still see the issue.
