### ISSUE TITLE
Last edited by

### ISSUE THREAD

**Issue by ReyKoxha** [pichalite/nodebb-theme-material#61]
![unbenannt](https://user-images.githubusercontent.com/13523850/26851102-2e8e7738-4b0a-11e7-8284-803eed30e9e1.PNG)

**Comment by bay1** [comment]
There's a temporary solution here！

>Custom CSS styles

![](https://s1.ax1x.com/2018/05/12/CBnu79.png)

achieve good results:alien:

![](https://s1.ax1x.com/2018/05/12/CBmxOg.png)
