### ISSUE TITLE
1.6.0 issues

### ISSUE THREAD

**Issue by barisusakli** [pichalite/nodebb-theme-material#71]
Not sure if some of these are specific to 1.6.0 but I will just list them here so I don't forget.

/search page doesn't show categories in the multi select
/unread /topic /recent possibly any page that imports pagination shows 2 arrows even if the page does not have enough items to paginate
last edited by text doesnt have margin
![image](https://user-images.githubusercontent.com/2583394/31368183-10a3d50e-ad4a-11e7-880e-33f1d9d0f280.png)

**Comment by pichalite** [comment]
https://github.com/pichalite/nodebb-theme-material/commit/34c9f79d73da4c580202fff8ef914ffb5180aa53
