### ISSUE TITLE
Support topic merging

### ISSUE THREAD

**Issue by bdharrington7** [pichalite/nodebb-theme-material#74]
Like in https://github.com/NodeBB/nodebb-theme-persona/commit/58ea2fb3bb53619039fe56d2b5ddee9354507fc1

**Comment by pichalite** [comment]
Available in latest version.

**Comment by bdharrington7** [comment]
@pichalite I must have missed it. Where is the option to merge topics? I went to categories -> General, then selected two topics, and no option appears to merge them. Also went to a topic and checked under topic tools at the bottom. I made sure to do another build too. Using the dark theme.

**Comment by pichalite** [comment]
When you go to categories -> general, open category tools and select merge topics option. A modal window opens up. Select topics and click merge.

**Comment by pichalite** [comment]
BTW, you need to click on the topic title to select topics instead of check boxes once the modal is open.

**Comment by bdharrington7** [comment]
That’s where I thought it would be, but it’s not there...
![807ee617-6ef1-4224-bcef-b75d39ab5f22](https://user-images.githubusercontent.com/4553795/35346876-56f1481a-00e8-11e8-9ef6-3b53df0e1e24.jpeg)

**Comment by bdharrington7** [comment]
Of course, in typical fashion, right after I post this, some cache or something was cleared and I can see the option in mobile and desktop now.

So I didn’t see it on mobile, and then I went to the site on desktop (new login on a computer I don’t usually use), and then the merge option showed up in both the desktop and mobile.
